app/mongo_odm.py, app/templates/base.html, app/templates/training_statistics.html, app/web_speech_trainer.py
Создана базовая версия страницы со статистикой тренировки.
Информация о тренировке, пока, представлена в виде заглушки. В дальнейшем её необходимо получать из базы данных и передавать в шаблон страницы.
=> Base version of training statistics page created

app/mongo_odm.py
Забыл добавить изменения из mongo_odm.py
=> [fix] [WST-30] Убрать кнопку Stop для окончания записи - автоматически заканчивать

app/api/trainings.py, app/routes/presentations.py, app/status.py
close #222 
Демо: https://youtu.be/iVT1FEizd_k
=> [WST-222] Add status IN_PROGRESS

app/criteria.py, app/criteria_pack.py
close #119 
Demo - https://youtu.be/Wy9LxZE2Xd0
=> Add primitive criteria

scripts/visualize.sh, visualization/db_getter.py, visualization/visualization.py
close #235
- Команда
```bash
./scripts/visualize.sh
```
- Результат: в директории ` visualization/retults/<current_date>`, графики:
=> [WST-235] Add script for plotting

app/criteria.py
#119 
Из-за бага #241 последний слайд почти всегда не удовлетворяет критерию (0 слов)
=> Add criteria for number of recognized words in audio

visualization/visualization.py
=> Add labels for hists

app/api/files.py, tests/mock_data.py
=> Add headers for audio

app/static/js/training_statistics.js, app/templates/training/statistics.html
=> Interactive audio 

app/api/trainings.py, app/routes/trainings.py, app/static/js/training.js, app/static/js/training_statistics.js, app/templates/training/statistics.html
=> Add preview and buttons to stats training page

app/api/trainings.py, app/routes/trainings.py, app/static/js/training.js, app/static/js/training_statistics.js, app/templates/training/statistics.html
close #254 
- set time by slide button
- set slide by time
=> Replay interface

scripts/db/mongo.sh
close #268 
```
-f      Don't include fs.chunks to backup
-a      Create two zips (with/without chunks)
```
=> Add new options for mongo.sh

app/api/files.py, app/utils.py, tests/api/test_files.py
=> New function for checking file mimetype

app/static/js/training.js, app/templates/training/statistics.html
=> Replace js-function call

app/api/sessions.py, app/mongo_odm.py, app/routes/lti.py, app/static/js/upload.js, app/utils.py
=> Add pres_formats to lti

app/api/dump.py, app/locale/en.json, app/routes/admin.py, app/templates/dumps.html, docker-compose.yml
- создание бакапов с/без fs-файлов разными кнопками/ссылками
- маппинг бакапов на хосте
=> Update backup approach

app/static/js/training_statistics.js
=> Fix audio timeupdate bug

Dockerfile, app/presentation_recognizer.py
=> Update presentation recognizers

Dockerfile
=> Fix python3 base image bugs

app/routes/lti.py, app/static/css/spinner.css, app/static/js/upload.js, app/templates/upload.html, app/web_speech_trainer.py
=> Update format notifications

app/api/version.py, app/routes/version.py
=> Open /version route

visualization/visualization.py
=> Add logs to visualization

app/static/js/upload.js
=> Update notification msg for convertible pres-formats

app/static/js/recording.js
close https://github.com/OSLL/web_speech_trainer/issues/290#issuecomment-912395855
=> Add logs for startRecording in js

app/api/trainings.py
=> Check generation_time of presentation_record_file_id

app/static/js/changeURL.js
=> Don't pushState url changes to history

app/static/js/changeURL.js
This reverts commit a40875ab12a4ededbac37feb3b0bbd205cb2262a, reversing
changes made to a2a509503dbfbe9e12b864e3117f55a12a70dad9.
=> Revert "Merge pull request #311 from OSLL/310_history_push"

app/api/files.py, app/criteria_pack/preconfigured_pack.py, app/static/js/show_all_presentations.js, app/templates/show_all_presentations.html, app/templates/training_greeting.html
close #278 
- увеличен размер превью презентации в задаче с фиксированной презентацией
- изображение превью - ссылка на файл презентации
- таблица всех презентаций
- содержит filename
- изображение превью - ссылка на файл презентации
=> Task with fixed pres

app/criteria/criterions.py, app/criteria/preconfigured_criterions.py, app/criteria/slides_checker/criterion.py, app/criteria_pack/preconfigured_pack.py, app/presentation_parser/odp_parser.py, app/presentation_parser/ppt_parser.py, app/static/js/criterion.js, app/templates/criterions.html
=> SlidesChecker criterion

app/api/trainings.py, app/routes/trainings.py, app/static/js/recording.js, app/static/js/show_all_trainings.js, app/templates/show_all_trainings.html, app/web_speech_trainer.py
close https://github.com/OSLL/web_speech_trainer/issues/229
Частично (позволяет переотправить одну кнопка переотправки в таблице для админов https://github.com/OSLL/web_speech_trainer/issues/338
=> Approbation fixes

docker-compose.yml
https://github.com/OSLL/linux-challenge/issues/825
=> Set mongo cache size 

.github/workflows/main.yml, app/static/css/training.css, app/static/js/recording.js, app/templates/training.html
После изменений до записи: ![перв](https://github.com/OSLL/web_speech_trainer/assets/71723580/3ec402f8-3cc2-4bd2-af35-82adf87a5758)
До изменений : ![До](https://github.com/OSLL/web_speech_trainer/assets/71723580/0c53b895-7fe8-4399-b655-ee5f6053a198)
После изменений во время записи: ![втор](https://github.com/OSLL/web_speech_trainer/assets/71723580/7d1d0aa0-3d9d-4c48-8c2d-d1b653c97809)
шрифт для: "Аудиозапись обрабатывается. Не уходите со страницы." - 36px, за место 14px
=> 362_fix_trainings_ui

app/static/css/training.css, app/static/js/recording.js, app/templates/training.html
=> 364_gif_record_add

app/static/js/recording.js
Попытка выйти до записи:
Попытка выйти во время записи:
Попытка выйти во время и после обработки:
=> 342_ask_close_window
